name: Deploy Angular to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read  # Necessário para acessar os arquivos do repositório.
  pages: write  # Necessário para fazer o deploy no GitHub Pages.

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build -- --prod  # Gera a build de produção na pasta "dist".

      - name: Upload production build
        uses: actions/upload-artifact@v3  # Versão atualizada
        with:
          name: angular-dist
          path: dist/projeto1-web2/  # Caminho correto da build

  deploy:
    needs: build  # O job deploy só começa após a conclusão do build.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: angular-dist
          branch: gh-pages
